/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAOHoaDon;
import static GUI.pnlhanghoa.lblCountPage;
import static GUI.pnlhanghoa.lblNumberPage;
import static GUI.pnlhanghoa.tblHoaDon;

/**
 *
 * @author Administrator
 */
public class jdlLocHoaDon extends javax.swing.JDialog {

    public static int countHD, soTrangHD, trangHD = 1;
    public int trangHD1 = 1;
    public static String MaNhanVien;
    public static String MaKhachHang;
    public static String TinhTrang;
    public static String TraHang;
    public static String CongNo;

    /**
     * Creates new form jdlLocHoaDon
     */
    public jdlLocHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlnenhotenkhachhang1 = new javax.swing.JPanel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pnlnenhotenkhachhang2 = new javax.swing.JPanel();
        cbbKhachHang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        pnlnenhotenkhachhang3 = new javax.swing.JPanel();
        cbbTinhTrang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pnlnenhotenkhachhang4 = new javax.swing.JPanel();
        cbbTraHang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pnlnenhotenkhachhang5 = new javax.swing.JPanel();
        cbbCongNo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LỌC HÓA ĐƠN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/filter_edit_20px.png"))); // NOI18N
        btnLoc.setText("     Lọc ngay");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lọc Hóa Đơn");

        pnlnenhotenkhachhang1.setBackground(new java.awt.Color(255, 255, 255));
        pnlnenhotenkhachhang1.setLayout(new java.awt.BorderLayout());

        cbbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả Nhân Viên" }));
        cbbNhanVien.setToolTipText("");
        cbbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbNhanVienMouseClicked(evt);
            }
        });
        pnlnenhotenkhachhang1.add(cbbNhanVien, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nhân Viên");
        pnlnenhotenkhachhang1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        pnlnenhotenkhachhang2.setBackground(new java.awt.Color(255, 255, 255));
        pnlnenhotenkhachhang2.setLayout(new java.awt.BorderLayout());

        cbbKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả Khách Hàng" }));
        cbbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbKhachHangMouseClicked(evt);
            }
        });
        pnlnenhotenkhachhang2.add(cbbKhachHang, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Khách Hàng");
        pnlnenhotenkhachhang2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        pnlnenhotenkhachhang3.setBackground(new java.awt.Color(255, 255, 255));
        pnlnenhotenkhachhang3.setLayout(new java.awt.BorderLayout());

        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại Tình Trạng" }));
        cbbTinhTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbTinhTrangMouseClicked(evt);
            }
        });
        pnlnenhotenkhachhang3.add(cbbTinhTrang, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tình Trạng");
        pnlnenhotenkhachhang3.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        pnlnenhotenkhachhang4.setBackground(new java.awt.Color(255, 255, 255));
        pnlnenhotenkhachhang4.setLayout(new java.awt.BorderLayout());

        cbbTraHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hình Thức Trả Hàng" }));
        cbbTraHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbTraHangMouseClicked(evt);
            }
        });
        pnlnenhotenkhachhang4.add(cbbTraHang, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Trả Hàng");
        pnlnenhotenkhachhang4.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        pnlnenhotenkhachhang5.setBackground(new java.awt.Color(255, 255, 255));
        pnlnenhotenkhachhang5.setLayout(new java.awt.BorderLayout());

        cbbCongNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tình Trạng Công Nợ" }));
        cbbCongNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbCongNoMouseClicked(evt);
            }
        });
        pnlnenhotenkhachhang5.add(cbbCongNo, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Công Nợ");
        pnlnenhotenkhachhang5.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlnenhotenkhachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlnenhotenkhachhang2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlnenhotenkhachhang3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlnenhotenkhachhang4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlnenhotenkhachhang5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlnenhotenkhachhang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlnenhotenkhachhang3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlnenhotenkhachhang4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlnenhotenkhachhang5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlnenhotenkhachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        if (cbbNhanVien.getSelectedItem().equals("Tất Cả Nhân Viên") && cbbKhachHang.getSelectedItem().equals("Tất Cả Khách Hàng") && cbbTinhTrang.getSelectedItem().equals("Loại Tình Trạng")
                && cbbTraHang.getSelectedItem().equals("Hình Thức Trả Hàng") && cbbCongNo.getSelectedItem().equals("Tình Trạng Công Nợ")) {
            ThongBaoCanhBao.ThongBao("Vui lòng chọn kiểu lọc hóa đơn!", "Thông Báo");
            return;

        }

        if (cbbNhanVien.getSelectedItem().equals("Tất Cả Nhân Viên")) {
            MaNhanVien = "";
        } else {
            int IDNhanVien = BLL.BLLHoaDon.LayMaNhanVienString(cbbNhanVien.getSelectedItem().toString());
            MaNhanVien = String.valueOf(IDNhanVien);
        }
        if (cbbKhachHang.getSelectedItem().equals("Tất Cả Khách Hàng")) {
            MaKhachHang = "";
        } else {
            int IDKhachHang = BLL.BLLHoaDon.LayMaKhachHangString(cbbKhachHang.getSelectedItem().toString());
            MaKhachHang = String.valueOf(IDKhachHang);
        }
        if (cbbTinhTrang.getSelectedItem().equals("Loại Tình Trạng")) {
            TinhTrang = "";
        } else {
            if (cbbTinhTrang.getSelectedItem().equals("Chưa Thanh Toán")) {
                TinhTrang = "0";
            } else if (cbbTinhTrang.getSelectedItem().equals("Đã Thanh Toán")) {
                TinhTrang = "1";
            } else {
                TinhTrang = "2";
            }
        }
        if (cbbTraHang.getSelectedItem().equals("Hình Thức Trả Hàng")) {
            TraHang = "";
        } else {
            if (cbbTraHang.getSelectedItem().equals("Đã Trả Hàng")) {
                TraHang = "0";
            } else {
                TraHang = "1";
            }
        }
        if (cbbCongNo.getSelectedItem().equals("Tình Trạng Công Nợ")) {
            CongNo = "like '%%'";
        } else {
            if (cbbCongNo.getSelectedItem().equals("Đang Nợ")) {
                CongNo = "!=0";
            } else {
                CongNo = "=0";
            }
        }
        DAOHoaDon.CountHoaDon();

        if (countHD % 13 == 0) {
            soTrangHD = countHD / 13;
        } else {
            soTrangHD = countHD / 13 + 1;
        }
        BLL.BLLHoaDon.HienThiHoaDonLoc(tblHoaDon, MaNhanVien, MaKhachHang, TinhTrang, TraHang, CongNo, 0);
        pnlhanghoa.LocHoaDon = "Đang Lọc";
        lblCountPage.setText(trangHD1 + "/" + soTrangHD + "");
        lblNumberPage.setText(trangHD1 + "");

        if (tblHoaDon.getRowCount() == 0) {
            ThongBaoCanhBao.ThongBao("Không tìm thấy hóa đơn phù hợp!", "Thông Báo");
        } else {
            ThongBaoCanhBao.ThongBao("Đã tìm thấy " + tblHoaDon.getRowCount() + " hóa đơn phù hợp!", "Thông Báo");
            this.dispose();
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void cbbTinhTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTinhTrangMouseClicked
        cbbTinhTrang.removeAllItems();
        cbbTinhTrang.addItem("Chưa Thanh Toán");
        cbbTinhTrang.addItem("Đã Thanh Toán");
        cbbTinhTrang.addItem("Đang Nợ");
    }//GEN-LAST:event_cbbTinhTrangMouseClicked

    private void cbbTraHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTraHangMouseClicked
        cbbTraHang.removeAllItems();
        cbbTraHang.addItem("Đã Trả Hàng");
        cbbTraHang.addItem("Chưa Trả Hàng");
    }//GEN-LAST:event_cbbTraHangMouseClicked

    private void cbbCongNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbCongNoMouseClicked
        cbbCongNo.removeAllItems();
        cbbCongNo.addItem("Đang Nợ");
        cbbCongNo.addItem("Không Nợ");
    }//GEN-LAST:event_cbbCongNoMouseClicked

    private void cbbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbNhanVienMouseClicked
        BLL.BLLHoaDon.DoDuLieuVaoCBBTenNguoiDung(cbbNhanVien);
    }//GEN-LAST:event_cbbNhanVienMouseClicked

    private void cbbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbKhachHangMouseClicked
        BLL.BLLHoaDon.DoDuLieuVaoCBBTenKhachHang(cbbKhachHang);
    }//GEN-LAST:event_cbbKhachHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlLocHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlLocHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlLocHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlLocHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlLocHoaDon dialog = new jdlLocHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JComboBox<String> cbbCongNo;
    private javax.swing.JComboBox<String> cbbKhachHang;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private javax.swing.JComboBox<String> cbbTraHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblhotenkhachhang;
    private javax.swing.JPanel pnlnenhotenkhachhang;
    private javax.swing.JPanel pnlnenhotenkhachhang1;
    private javax.swing.JPanel pnlnenhotenkhachhang2;
    private javax.swing.JPanel pnlnenhotenkhachhang3;
    private javax.swing.JPanel pnlnenhotenkhachhang4;
    private javax.swing.JPanel pnlnenhotenkhachhang5;
    private javax.swing.JTextField txtHoTen;
    // End of variables declaration//GEN-END:variables
}
